site_name: FF's Blog
site_url: https://fightingff.github.io/Projects/Blog
nav:
  - Home: index.md
  - Asm: ASM.md 
  - Digit Logic: DigitLogic.md
theme:
  name: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
